# Generated by Django 3.0.5 on 2020-04-24 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0004_contentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentimage',
            name='content_image',
            field=models.ImageField(upload_to='post_content_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
